### PR TITLE
Work Topics and Deprovision Fixes

### LINKED ISSUE #341: Deprovision of hello-world APB fails with "token provided is invalid or expired"
> ### Bug: Deprovision of hello-world APB fails with "token provided is invalid or expired"

Possibly related to issue https://github.com/openshift/ansible-service-broker/issues/342

**What happened**:

- Reset catasb cluster
- Provision hello-world APB from apb-examples into a new project "project1"
- Wait for provision APB run to complete successfully
- Attempt deprovision action
- Deprovision pod fails with "The token provided is invalid or expired."

[Link to ASB logs](https://paste.fedoraproject.org/paste/3Xeeqng7Ziuce3L34mgdjg)

APB provision logs:
```

  | + [[ provision --extra-vars {"_apb_plan_id":"default","namespace":"project1"} == *\s\2\i\/\a\s\s\e\m\b\l\e* ]]
  | + ACTION=provision
  | + shift
  | + playbooks=/opt/apb/actions
  | + CREDS=/var/tmp/bind-creds
  | + whoami
  | + '[' -w /etc/passwd ']'
  | ++ id -u
  | + echo 'apb:x:1000080000:0:apb user:/opt/apb:/sbin/nologin'
  | + oc-login.sh
  | Attempting to login with a service account...
  | Logged into "https://kubernetes.default:443" as "system:serviceaccount:project1:apb-0d8932e5-3920-4ebe-a773-0dc997535420" using the token provided.
  | You have one project on this server: "project1"
  | Using project "project1".
  | Welcome! See 'oc help' to get started.
  | + [[ -e /opt/apb/actions/provision.yaml ]]
  | + [[ -e /opt/apb/actions/provision.yml ]]
  | + ansible-playbook /opt/apb/actions/provision.yml --extra-vars '{"_apb_plan_id":"default","namespace":"project1"}'
  | PLAY [hello-world-apb provision] ***********************************************
  | TASK [ansible.kubernetes-modules : Intall latest openshift client] *************
  | skipping: [localhost]
  | TASK [provision-hello-world-apb : create deployment config] ********************
  | changed: [localhost]
  | TASK [provision-hello-world-apb : create hello-world service] ******************
  | changed: [localhost]
  | TASK [provision-hello-world-apb : create hello-world route] ********************
  | changed: [localhost]
  | PLAY RECAP *********************************************************************
  | localhost                  : ok=3    changed=3    unreachable=0    failed=0
  | + '[' -f /var/tmp/bind-creds ']'
```

APB deprovision logs:
```

  | + [[ deprovision --extra-vars {"_apb_plan_id":"default","namespace":"project1"} == *\s\2\i\/\a\s\s\e\m\b\l\e* ]]
  | + ACTION=deprovision
  | + shift
  | + playbooks=/opt/apb/actions
  | + CREDS=/var/tmp/bind-creds
  | + whoami
  | + '[' -w /etc/passwd ']'
  | ++ id -u
  | + echo 'apb:x:1000080000:0:apb user:/opt/apb:/sbin/nologin'
  | + oc-login.sh
  | Attempting to login with a service account...
  | error: The token provided is invalid or expired.

```

**What you expected to happen**:
Same sequence, but deprovision action completes successfully.

### PR DESCRIPTION
**Pull request by eriknelson**
* Added topics to work engine
* Added deprovision subscriber, make sure the ProvisionSubscriber stops
processing deprovision messages as previously written
* Added pod watcher for actions that don't require cred extraction
but still need to watch for completion and handle
* Various refactoring to leverage new stuff

**Which issue this PR fixes (This will close that issue when PR gets merged)**
fixes #341

### CODE REVIEW

File: pkg/app/app.go [hunk 1]
```diff
@@ -116,8 +116,13 @@ func CreateApp() App {
...
 	app.engine = broker.NewWorkEngine(MsgBufferSize)
-	app.log.Debug("Initializing Provision WorkSubscriber")
-	app.engine.AttachSubscriber(broker.NewProvisionWorkSubscriber(app.dao, app.log.Logger))
+	app.engine.AttachSubscriberToTopic(
+		broker.NewProvisionWorkSubscriber(app.dao, app.log.Logger),
+		broker.ProvisionTopic)
+	app.engine.AttachSubscriberToTopic(
+		broker.NewDeprovisionWorkSubscriber(app.dao, app.log.Logger),
+		broker.DeprovisionTopic)
+	app.log.Debugf("Active work engine topics: %+v", app.engine.GetActiveTopics())
```
Comment (jmrodri) [inline pkg/app/app.go]: +1 to all of the above.

File: pkg/broker/work_engine.go [hunk 2]
```diff
@@ -7,32 +7,59 @@ type Work interface {
...
+	return &WorkEngine{topics: make(map[WorkTopic]chan WorkMsg)}
 }
 
-// StartNewJob - Starts a job in an new goroutine. returns token, or generated token if an empty token is passed in.
-func (engine *WorkEngine) StartNewJob(token string, work Work) string {
+//msgBuffer: make(chan WorkMsg, bufferSize),
+
+// StartNewJobOnTopic - Starts a job in an new goroutine, reporting to a specific topic.
+// returns token, or generated token if an empty token is passed in.
+func (engine *WorkEngine) StartNewJobOnTopic(
```
Comment (jmrodri) [inline pkg/broker/work_engine.go]: I would've left it StartNewJob just because there isn't another type.

File: pkg/broker/work_engine.go [hunk 3]
```diff
@@ -7,32 +7,59 @@ type Work interface {
...
 	return jobToken
 }
 
-// AttachSubscriber - Attach a subscriber to the engine. Will send the WorkMsg to the subscribers through the message buffer.
-func (engine *WorkEngine) AttachSubscriber(subscriber WorkSubscriber) {
-	subscriber.Subscribe(engine.msgBuffer)
+// AttachSubscriberToTopic - Attach a subscriber a specific messaging topic.
+// Will send the WorkMsg to the subscribers through the message buffer.
+func (engine *WorkEngine) AttachSubscriberToTopic(
+	subscriber WorkSubscriber, topic WorkTopic,
```
Comment (jmrodri) [inline pkg/broker/work_engine.go]: You could've left it AttachSubscriber since we're simply just changing what it means to attach a subscriber. Yes it is more descriptive but I can see by the signature that we need to pass in a topic.

File: pkg/broker/work_engine.go [hunk 4]
```diff
@@ -7,32 +7,59 @@ type Work interface {
 	Run(token string, msgBuffer chan<- WorkMsg)
 }
 
+// WorkTopic - Topic jobs can publish messages to, and subscribers can listen to
+type WorkTopic string
+
 // WorkEngine - a new engine for doing work.
 type WorkEngine struct {
-	msgBuffer chan WorkMsg
+	topics map[WorkTopic]chan WorkMsg
```
Comment (jmrodri) [inline pkg/broker/work_engine.go]: +1 to WorkTopic

File: pkg/broker/work_engine.go [hunk 5]
```diff
@@ -7,32 +7,59 @@ type Work interface {
...
 }
 
 // NewWorkEngine - creates a new work engine
 func NewWorkEngine(bufferSize int) *WorkEngine {
-	return &WorkEngine{
-		msgBuffer: make(chan WorkMsg, bufferSize),
-	}
+	return &WorkEngine{topics: make(map[WorkTopic]chan WorkMsg)}
```
Comment (jmrodri) [inline pkg/broker/work_engine.go]: +1 to format change. I think I carried the above from cap :)

File: pkg/broker/broker.go [hunk 6]
```diff
@@ -315,7 +315,7 @@ func (a AnsibleBroker) Recover() (string, error) {
 
 			// Need to use the same token as before, since that's what the
 			// catalog will try to ping.
-			a.engine.StartNewJob(rs.State.Token, pjob)
+			a.engine.StartNewJobOnTopic(rs.State.Token, pjob, ProvisionTopic)
```
Comment (jmrodri) [inline pkg/broker/broker.go]: Is there still a `StartNewJob`?

Comment (jmrodri) [inline pkg/broker/broker.go]: Actually saw that there is no StartNewJob, see comment about WorkEngine

File: pkg/broker/broker.go [hunk 7]
```diff
@@ -596,47 +596,26 @@ func (a AnsibleBroker) Deprovision(
...
-func cleanupDeprovision(err error, podName string, instance *apb.ServiceInstance, dao *dao.Dao,
-	log *logging.Logger,
-) error {
-	instanceID := instance.ID.String()
-	sm := apb.NewServiceAccountManager(log)
-	log.Info("Destroying APB sandbox...")
-	sm.DestroyApbSandbox(podName, instance.Context.Namespace)
 
-	// bubble up error.
+	err = cleanupDeprovision(podName, instance, a.dao, a.log)
```
Comment (jmrodri) [inline pkg/broker/broker.go]: much nicer

File: pkg/broker/deprovision_job.go [hunk 8]
```diff
@@ -44,20 +45,15 @@ func NewDeprovisionJob(serviceInstance *apb.ServiceInstance, clusterConfig apb.C
...
+		msgBuffer <- DeprovisionMsg{InstanceUUID: p.serviceInstance.ID.String(), PodName: podName,
 			JobToken: token, SpecID: p.serviceInstance.Spec.ID, Error: err.Error()}
 		return
 	}
 
-	// send creds
-	p.log.Debug("sending message to channel")
-	msgBuffer <- DeprovisionMsg{InstanceUUID: p.serviceInstance.ID.String(),
+	p.log.Debug("sending deprovision complete msg to channel")
+	msgBuffer <- DeprovisionMsg{InstanceUUID: p.serviceInstance.ID.String(), PodName: podName,
```
Comment (jmrodri) [inline pkg/broker/deprovision_job.go]: Change looks good.

File: pkg/broker/provision_job.go [hunk 9]
```diff
@@ -47,7 +47,7 @@ func (p *ProvisionJob) Run(token string, msgBuffer chan<- WorkMsg) {
 
 	if err != nil {
 		p.log.Error("broker::Provision error occurred.")
-		p.log.Error("%s", err.Error())
+		p.log.Errorf("%s", err.Error())
```
Comment (jmrodri) [inline pkg/broker/provision_job.go]: +1 to the Errorf

File: pkg/broker/provision_job.go [hunk 10]
```diff
@@ -59,15 +59,17 @@ func (p *ProvisionJob) Run(token string, msgBuffer chan<- WorkMsg) {
...
 	sm.DestroyApbSandbox(podName, p.serviceInstance.Context.Namespace)
 
 	// send creds
-	jsonmsg, _ := json.Marshal(extCreds)
-	p.log.Debug("sending message to channel")
+	jsonmsg, err := json.Marshal(extCreds)
+	if err != nil {
+		msgBuffer <- ProvisionMsg{InstanceUUID: p.serviceInstance.ID.String(),
+			JobToken: token, SpecID: p.serviceInstance.Spec.ID, PodName: "", Msg: "", Error: err.Error()}
+		return
```
Comment (jmrodri) [inline pkg/broker/provision_job.go]: Hah I can't believe we were ignoring the error on Marshal. um this is definitely needed.

File: pkg/broker/provision_subscriber.go [hunk 11]
```diff
@@ -31,21 +31,25 @@ func (p *ProvisionWorkSubscriber) Subscribe(msgBuffer <-chan WorkMsg) {
...
 				// state. Since we'll also be using this to get more granular
 				// updates one day.
-				p.dao.SetState(pmsg.InstanceUUID, apb.JobState{Token: pmsg.JobToken, State: apb.StateInProgress, Podname: pmsg.PodName})
+				p.dao.SetState(pmsg.InstanceUUID, apb.JobState{Token: pmsg.JobToken,
+					State: apb.StateInProgress, Podname: pmsg.PodName})
 			} else {
 				json.Unmarshal([]byte(pmsg.Msg), &extCreds)
-				p.dao.SetState(pmsg.InstanceUUID, apb.JobState{Token: pmsg.JobToken, State: apb.StateSucceeded, Podname: pmsg.PodName})
+				p.dao.SetState(pmsg.InstanceUUID, apb.JobState{Token: pmsg.JobToken,
+					State: apb.StateSucceeded, Podname: pmsg.PodName})
```
Comment (jmrodri) [inline pkg/broker/provision_subscriber.go]: without the formatting changes this diff would've been simpler :) looks like it was just the Errorf addition since all the SetStates look the same.

File: pkg/broker/work_engine.go [hunk 12]
```diff
@@ -7,32 +7,59 @@ type Work interface {
...
+// AttachSubscriberToTopic - Attach a subscriber a specific messaging topic.
+// Will send the WorkMsg to the subscribers through the message buffer.
+func (engine *WorkEngine) AttachSubscriberToTopic(
+	subscriber WorkSubscriber, topic WorkTopic,
+) {
+	msgBuffer, topicExists := engine.topics[topic]
+	if !topicExists {
+		msgBuffer = make(chan WorkMsg)
+		engine.topics[topic] = msgBuffer
+	}
```
Comment (jmrodri) [inline pkg/broker/work_engine.go]: this section confuses me. We do this in the Start, what's the reason for doing it again in the Subscribe? Why wouldn't this already be done?

Comment (eriknelson) [inline pkg/broker/work_engine.go]: I was trying to think of the engine as a generic utility here; maybe it will get used differently than we're using it at some point in the future. Work engine jobs could get started on topics that don't already exist, and subscribers could be attached to engines on topics that don't already exist. This just makes sure regardless of which is called first, the topic is there and the dependency is available.

Reading over it again though, I don't think this is thread safe... it could probably use some kind of `Once` sync, although we're safe with our particular usage.

In our specific case, `AttachSubscriberToTopic` calls both occur before any jobs are ever started (in `CreateApp`). `provision_topic` and `deprovision_topic` going to be created and cached so the `StartJob` calls will get hits and use the existing ones.

File: pkg/broker/work_engine.go (hunk 3 above)
Comment (eriknelson) [inline pkg/broker/work_engine.go]: Good point.

File: pkg/apb/deprovision.go [hunk 13]
```diff
@@ -33,12 +35,17 @@ func Deprovision(instance *ServiceInstance, clusterConfig ClusterConfig, log *lo
...
 	if err != nil {
 		log.Error("Problem executing apb %s", err)
 		return podName, err
 	}
 
-	log.Info(string(podName))
+	podOutput, err := watchPod(podName, instance.Context.Namespace, log)
+	if err != nil {
+		log.Error("Error returned from watching pod")
+		log.Errorf("error: %s", err.Error())
```
Comment (eriknelson) [inline pkg/apb/deprovision.go]: Heh, this comes up in a lot of my reviews, it's a preference. I'll update with the first.

File: pkg/apb/deprovision.go [hunk 14]
```diff
@@ -33,12 +35,17 @@ func Deprovision(instance *ServiceInstance, clusterConfig ClusterConfig, log *lo
 		"deprovision", clusterConfig, instance.Spec,
 		instance.Context, instance.Parameters, log,
 	)
-
```
Comment (eriknelson) [inline pkg/apb/deprovision.go]: Eh, I probably absent-mindedly did this. Visually I think I like it because it associates the error handler with the line that triggered it.

File: pkg/apb/deprovision.go [hunk 15]
```diff
@@ -6,7 +6,9 @@ import (
 )
 
 // Deprovision - runs the abp with the deprovision action.
-func Deprovision(instance *ServiceInstance, clusterConfig ClusterConfig, log *logging.Logger) (string, error) {
+func Deprovision(
+	instance *ServiceInstance, clusterConfig ClusterConfig, log *logging.Logger,
+) (string, error) {
```
Comment (eriknelson) [inline pkg/apb/deprovision.go]: I'll try to keep formatting stuff separate in the future.

File: pkg/apb/ext_creds.go [hunk 16]
```diff
@@ -63,9 +60,10 @@ func monitorOutput(namespace string, podname string, log *logging.Logger) ([]byt
 		}
 
 		log.Warning("[%s] Retry attempt %d: exec into %s failed", podname, r, podname)
-		time.Sleep(time.Duration(credentialExtInterval) * time.Second)
+		time.Sleep(time.Duration(apbWatchInterval) * time.Second)
 	}
-	timeout := fmt.Sprintf("[%s] ExecTimeout: Failed to gather bind credentials after %d retries", podname, credentialExtRetries)
+
+	timeout := fmt.Sprintf("[%s] ExecTimeout: Failed to gather bind credentials after %d retries", podname, apbWatchRetries)
```
Comment (eriknelson) [inline pkg/apb/ext_creds.go]: Renamed because they are now used in two places, one has nothing to do with credentials.

**Comment by eriknelson** [comment]
Somehow the deprovision_subscriber is missing from this commit, but my local system seems to think it's been checked in and isn't a new file. Trying to figure out what's going on there.

**Comment by eriknelson** [comment]
Wow. Turns out we were ignoring anything new in `pkg/broker` with an [overzealous](https://github.com/openshift/ansible-service-broker/blob/master/.gitignore#L340) `.gitignore`.

Also learned about `git check-ignore -v`, super helpful debugging that! I updated the `.gitignore` to **not** ignore `pkg/broker`.

File: pkg/broker/work_engine.go [hunk 17]
```diff
@@ -7,32 +7,57 @@ type Work interface {
 	Run(token string, msgBuffer chan<- WorkMsg)
 }
 
+// WorkTopic - Topic jobs can publish messages to, and subscribers can listen to
+type WorkTopic string
```
Comment (shawn-hurley) [inline pkg/broker/work_engine.go]: Can we keep the type declaration near the const definition? Will be easier for people reading godoc, or code, that it is supposed to be a kind of enum IMO.

File: pkg/broker/work_engine.go (hunk 12 above)
Comment (shawn-hurley) [inline pkg/broker/work_engine.go]: At least we need to check that the topic is in the enum IMO. I can see the value in lazy initialization here but if we are using an enum to make sure only certain work topics are allowed then we need to check it because 
```go
WorkTopic("somethingNewTopic")
```
is a valid work topic to the compiler.

File: pkg/apb/deprovision.go (hunk 15 above)
Comment (jmrodri) [inline pkg/apb/deprovision.go]: Thanks I don't mind the formatting in general but it's distracting when it is purely a format change.

File: pkg/apb/deprovision.go (hunk 14 above)
Comment (jmrodri) [inline pkg/apb/deprovision.go]: We can remove the line, it does make it easier.

File: pkg/apb/watch_pod.go [hunk 18]
```diff
@@ -0,0 +1,52 @@
...
+		} else if didPodError {
+			return outStr, fmt.Errorf("Pod %s is reporting error", podName)
+		} else if didPodComplete {
+			return outStr, nil
+		} else if isPodRunning {
+			log.Info("Pod %s still running, continuing to watch", podName)
+		} else {
+			log.Info("Pod completion not found, continuing to watch")
+			log.Infof("%s", outStr)
+		}
```
Comment (jmrodri) [inline pkg/apb/watch_pod.go]: > This conditional looks just good.

I have no idea what I was trying to say there :) ignore it.

File: pkg/broker/work_engine.go (hunk 12 above)
Comment (jmrodri) [inline pkg/broker/work_engine.go]: @eriknelson thanks for the explanation that helps a lot.

File: .gitignore [hunk 19]
```diff
@@ -33,6 +33,7 @@ etc/mock.config.yaml
 #Compiled binaries
 broker
 build/broker
+!pkg/broker
```
Comment (jmrodri) [inline .gitignore]: `./broker` works too it's that executable that caused the problem. Good catch.

Comment (eriknelson) [inline .gitignore]: @jmrodri that didn't work for me actually.

File: pkg/apb/deprovision.go (hunk 15 above)
Comment (eriknelson) [inline pkg/apb/deprovision.go]: Agreed, I know we've had the same conversation about other PRs. Definitely makes it easier to review.

File: pkg/broker/deprovision_subscriber.go [hunk 20]
```diff
@@ -0,0 +1,99 @@
...
+
+func setFailedDeprovisionJob(dao *dao.Dao, dmsg *DeprovisionMsg) {
+	dao.SetState(dmsg.InstanceUUID, apb.JobState{
+		Token:   dmsg.JobToken,
+		State:   apb.StateFailed,
+		Podname: dmsg.PodName,
+	})
+}
+
+func cleanupDeprovision(
```
Comment (jmrodri) [inline pkg/broker/deprovision_subscriber.go]: Perfect place for this.

File: pkg/broker/deprovision_subscriber.go [hunk 21]
```diff
@@ -0,0 +1,99 @@
...
+				return
+			}
+
+			// No errors reported, deprovision action successfully performed and
+			// broker has successfully cleaned up. Mark depro success
+			d.dao.SetState(dmsg.InstanceUUID, apb.JobState{Token: dmsg.JobToken,
+				State: apb.StateSucceeded, Podname: dmsg.PodName})
+		}
+	}()
+}
```
Comment (jmrodri) [inline pkg/broker/deprovision_subscriber.go]: Looks good to me.

File: pkg/broker/types.go [hunk 22]
```diff
@@ -15,12 +15,26 @@ const (
...
+// WorkTopic - Topic jobs can publish messages to, and subscribers can listen to
+type WorkTopic string
+
 // Work Engine messaging consts
 const (
 	ProvisionTopic   WorkTopic = "provision_topic"
 	DeprovisionTopic WorkTopic = "deprovision_topic"
 )
 
+var workTopicSet = map[WorkTopic]bool{
```
Comment (shawn-hurley) [inline pkg/broker/types.go]: :+1: :100:
