### PR TITLE
Bug 1536629 - send job state and credentials from job

### LINKED ISSUE #608: JobState should be sent as part of the JobMsg rather than be set by the subscribers
> # Feature:
As discussed on IRC with @eriknelson, while looking at the last operation PR it occurred to me it would make more sense to have the Job send through the JobState as part of its msg that is consumed by the subscribers rather than the subscribers deciding what state to set as can be seen here: https://github.com/openshift/ansible-service-broker/blob/master/pkg/broker/provision_subscriber.go#L55  
I intended to include this change in my main PR for the last_operation feature, but after discussion, it probably makes more sense to have it as a standalone PR.

### PR DESCRIPTION
**Pull request by maleck13**
**Note for Reviewer**
There are two commits here
1) making the changes required
2) adding a set of test for the provision subscriber and job. If happy with the approach here I will expand the tests to cover the other subscribers and jobs.  Making a number of changes like this, I felt a little disconcerted that I had no unit test to run so would love to add more to help protect against regressions in future changes.

These commits are independent of each other so if the new tests are not wanted I can remove.

I am currently trying this out in my local cluster but wanted to create the PR to let the integration tests run.

**Describe what this PR does and why we need it**:
The subscribers were deciding on the state of the Job, rather than the job informing the subscriber of the job state.  This pr follows on from issue https://github.com/openshift/ansible-service-broker/issues/608
Also the Job was Marshalling the extracted credentials and sending them as a string on the Msg field, then the subscriber would Unmarshal it and save it. Instead of doing this we just send the credentials through

Changes proposed in this pull request
 - simplify subscriber logic
 - send state from the individual job
 - send credentials directly via the Job rather than turning them into a JSON string and then back to credentials again in the subscriber (avoid unneeded marshalling and unmarshalling)
- Make an attempt at adding test cases for the ProvisionJob as an example for how it might be done and to get feedback on the approach 

**Which issue this PR fixes (This will close that issue when PR gets merged)**
fixes #608

### CODE REVIEW

**Comment by maleck13** [comment]
@eriknelson PR from conversation on IRC yesterday about subscribers setting state.

**Comment by maleck13** [comment]
This pr is also part of the larger work being done for https://github.com/openshift/ansible-service-broker/issues/475

**Comment by shawn-hurley** [comment]
This looks really good to me, want to discuss the provisioner type being defined in the apb package.

I like the way you have made it testable by making the `provisioner` function. That looks really correct to me, and I think that we should make a not to update the `deprovision` and `update` jobs with this style.

File: pkg/broker/provision_subscriber.go [hunk 1]
```diff
@@ -17,76 +17,35 @@
...
-	"github.com/openshift/ansible-service-broker/pkg/dao"
-	"github.com/openshift/ansible-service-broker/pkg/metrics"
 )
 
-// ProvisionWorkSubscriber - Lissten for provision messages
+// ProvisionWorkSubscriber - Listen for provision messages
 type ProvisionWorkSubscriber struct {
-	dao       *dao.Dao
-	msgBuffer <-chan JobMsg
+	dao SubcriberDAO
```
Comment (rthallisey) [inline pkg/broker/provision_subscriber.go]: s/SubcriberDAO/SubscriberDAO/

**Comment by rthallisey** [comment]
@mhrivnak if you change your initial commit to say ```fixes #608``` instead of ```608``` it will automatically close the git issue after this PR merges.

File: pkg/broker/provision_job.go [hunk 2]
```diff
@@ -17,64 +17,66 @@
...
 )
 
 // ProvisionJob - Job to provision
 type ProvisionJob struct {
 	serviceInstance *apb.ServiceInstance
+	provision       Provisioner
 }
 
+// Provisioner defines a function that knows how to provision an apb
+type Provisioner func(si *apb.ServiceInstance) (string, *apb.ExtractedCredentials, error)
```
[the remark this answers is not in the document]
Comment (maleck13) [reply pkg/broker/provision_job.go]: yeah no issue with that.

**Comment by jmrodri** [comment]
I'll review this and see what the impact is on my current outstanding async work. I'm currently knee deep in this area.

**Comment by mhrivnak** [comment]
> @mhrivnak if you change your initial commit to say fixes #608 instead of 608 it will automatically close the git issue after this PR merges.

I assume that comment is for @maleck13

**Comment by maleck13** [comment]
@shawn-hurley Will wait for @jmrodri review before changing the location of the provision type, in case there are further changes required. 
I think if all is good after the reviews perhaps we should merge at that point and I can follow up with the tests for the remaining subscribers and jobs? Just trying to avoid to big of a rebase and merge for others. If not I can do it on this PR not a big deal either way

**Comment by shawn-hurley** [comment]
@maleck13 👍 for waiting for @jmrodri. If you want to follow up with the changes you can take it, but I wouldn't mind taking it off your plate if you want to work on your other PR? Completely up to you just offering my help if you want it.

**Comment by maleck13** [comment]
@shawn-hurley thanks for the offer. I think though I will naturally end up creating the additional tests as part of the PR work as I want to be able to run them when iterating on the feature pr and a good bit of the work for the last operation feature is around the Jobs and subscribers.

**Comment by rthallisey** [comment]
Partially: https://github.com/openshift/ansible-service-broker/issues/542

File: pkg/broker/deprovision_subscriber.go [hunk 3]
```diff
@@ -36,64 +35,40 @@ func NewDeprovisionWorkSubscriber(dao *dao.Dao) *DeprovisionWorkSubscriber {
...
-			if err != nil {
-				log.Errorf(
-					"Error occurred getting service instance [ %s ] after deprovision job:",
-					msg.InstanceUUID,
-				)
-				setFailedDeprovisionJob(d.dao, msg)
-				continue
+		for msg := range msgBuffer {
+			log.Debug("received deprovision message from buffer")
+			if msg.State.State == apb.StateSucceeded {
```
Comment (jmrodri) [inline pkg/broker/deprovision_subscriber.go]: I would flip the check to look for the error conditions first and have escape valves, then do the success case afterwards without being in an if block.

```golang
func (d *DeprovisionWorkSubscriber) Subscribe(msgBuffer <-chan JobMsg) {
    d.msgBuffer = msgBuffer
    go func() {
        log.Info("Listening for deprovision messages")
        for msg := range msgBuffer {
            log.Debug("received deprovision message from buffer")

            if msg.State.State != apb.StateSucceeded { 
                if err := d.dao.SetState(msg.InstanceUUID, msg.State); err != nil {
                    log.Errorf("failed to set state after deprovision %v", err)
                }
                continue
            }

            instance, err := d.dao.GetServiceInstance(msg.InstanceUUID)
            if err != nil {
                log.Errorf(
                    "Error occurred getting service instance [ %s ] after deprovision job:",
                    msg.InstanceUUID,
                )   
                setFailedDeprovisionJob(d.dao, msg)
                continue
            }
            if err := cleanupDeprovision(instance, d.dao); err != nil {
                log.Errorf("Failed cleaning up deprovision after job, error: %v", err)
                // Cleanup is reporting something has gone wrong. Deprovision overall
                // has not completed. Mark the job as failed.
                setFailedDeprovisionJob(d.dao, msg)
                continue
            }   
        }
    }()
}

```

File: pkg/broker/deprovision_subscriber.go [hunk 4]
```diff
@@ -36,64 +35,40 @@ func NewDeprovisionWorkSubscriber(dao *dao.Dao) *DeprovisionWorkSubscriber {
...
-	if err := dao.SetState(dmsg.InstanceUUID, apb.JobState{
-		Token:   dmsg.JobToken,
-		State:   apb.StateFailed,
-		Podname: dmsg.PodName,
-		Method:  apb.JobMethodDeprovision,
-		Error:   dmsg.Error,
-	}); err != nil {
-		log.Errorf("failed to set state after deprovision %#v", err)
+	// have to set the state here manually as the logic that triggers this is in the subscriber
+	dmsg.State.State = apb.StateFailed
```
Comment (jmrodri) [inline pkg/broker/deprovision_subscriber.go]: The stutter is definitely weird. If we don't want to add the method, then `dmsg.JobState.State` might work.

File: pkg/broker/deprovision_subscriber.go [hunk 5]
```diff
@@ -102,12 +77,12 @@ func cleanupDeprovision(instance *apb.ServiceInstance, dao *dao.Dao) error {
 	id := instance.ID.String()
 
 	if err = dao.DeleteExtractedCredentials(id); err != nil {
-		log.Error("failed to delete extracted credentials - %#v", err)
+		log.Error("failed to delete extracted credentials - %v", err)
```
Comment (jmrodri) [inline pkg/broker/deprovision_subscriber.go]: any reason you changed from `%#v` to `%v`? @shawn-hurley I think I've seen you use the `%#v` variant, thoughts?

File: pkg/broker/provision_subscriber.go [hunk 6]
```diff
@@ -17,76 +17,35 @@
...
 import (
-	"encoding/json"
-
 	"github.com/openshift/ansible-service-broker/pkg/apb"
 	"github.com/openshift/ansible-service-broker/pkg/dao"
-	"github.com/openshift/ansible-service-broker/pkg/metrics"
 )
 
-// ProvisionWorkSubscriber - Lissten for provision messages
+// ProvisionWorkSubscriber - Listen for provision messages
```
Comment (jmrodri) [inline pkg/broker/provision_subscriber.go]: 👍 to fixing typos

File: pkg/broker/deprovision_job.go [hunk 7]
```diff
@@ -43,42 +43,44 @@ func NewDeprovisionJob(serviceInstance *apb.ServiceInstance,
 // Run - will run the deprovision job.
 func (p *DeprovisionJob) Run(token string, msgBuffer chan<- JobMsg) {
 	metrics.DeprovisionJobStarted()
+	defer metrics.DeprovisionJobFinished()
+	var jobMsg = JobMsg{
```
[the remark this answers is not in the document]
Comment (maleck13) [reply pkg/broker/deprovision_job.go]: Nothing specific, just a habit I have as it is accessed from several blocks within the function. Happy to change it

File: pkg/broker/deprovision_job.go [hunk 8]
```diff
@@ -43,42 +43,44 @@ func NewDeprovisionJob(serviceInstance *apb.ServiceInstance,
...
+			Method: apb.JobMethodDeprovision,
+			Token:  token,
+		},
+	}
 
 	if p.skipApbExecution {
 		log.Debug("skipping deprovision and sending complete msg to channel")
-		msgBuffer <- JobMsg{InstanceUUID: p.serviceInstance.ID.String(), PodName: "",
-			JobToken: token, SpecID: p.serviceInstance.Spec.ID, Error: ""}
+		jobMsg.State.State = apb.StateSucceeded
```
[the remark this answers is not in the document]
Comment (maleck13) [reply pkg/broker/deprovision_job.go]: Agree on stuttering struggled with it also, but not a big fan of using setters either though. I wondered if perhaps we could remove JobMsg entirely and just have JobState as their is some duplication between them?

File: pkg/broker/deprovision_subscriber.go [hunk 9]
```diff
@@ -36,64 +35,40 @@ func NewDeprovisionWorkSubscriber(dao *dao.Dao) *DeprovisionWorkSubscriber {
...
-
-			instance, err := d.dao.GetServiceInstance(msg.InstanceUUID)
-			if err != nil {
-				log.Errorf(
-					"Error occurred getting service instance [ %s ] after deprovision job:",
-					msg.InstanceUUID,
-				)
-				setFailedDeprovisionJob(d.dao, msg)
-				continue
+		for msg := range msgBuffer {
```
[the remark this answers is not in the document]
Comment (maleck13) [reply pkg/broker/deprovision_subscriber.go]: 2 reasons:
1) When you close a channel and you use the for range method, the loop also closes, where as if you just use a for loop and receive from the channel, once the channel is closed you will continue to receive the default value for that channel. If you don't want that behaviour your code would need to check the second value on a channel receive:
```
msg,closed <- chan 
if closed{
break
}
```
https://dave.cheney.net/2014/03/19/channel-axioms

2) I am ok with checking if the channel is closed, but in my opinion it also reads a little better with the range statement.

File: pkg/broker/deprovision_subscriber.go (hunk 3 above)
Comment (maleck13) [reply pkg/broker/deprovision_subscriber.go]: 👍

File: pkg/broker/deprovision_subscriber.go (hunk 4 above)
Comment (maleck13) [reply pkg/broker/deprovision_subscriber.go]: Yeah thought about doing that also, but see above comment on perhaps removing the ```JobMsg``` and just having ```JobState.State```

File: pkg/broker/deprovision_subscriber.go (hunk 5 above)
Comment (maleck13) [reply pkg/broker/deprovision_subscriber.go]: There seemed to be different approaches to this across the code base with ```%v``` seeming to be the most common. In my opinion, the %v is good for error messages as it will just print the error string, where as perhaps the %#v is good for debug statements as it prints the struct
```
&errors.errorString{s:"test error"}
```
see example https://play.golang.org/p/nkVaxztAG4_I

File: pkg/broker/deprovision_job.go (hunk 8 above)
[the remark this answers is not in the document]
Comment (maleck13) [reply pkg/broker/deprovision_job.go]: On a side note, I think we could simplify things by removing the subscribers and either have a set of observers registered for each job that act on JobState changes or simply give the Job access to the DAO to set the state itself. 
Maybe better to discuss this outside of this PR though.

[the remark this answers is not in the document]
Comment (rthallisey) [reply pkg/broker/deprovision_job.go]: I think it's worth a discussion @maleck13. I don't remember the issue where you first mentioned this idea, but it's worth bringing it up again.

[the remark this answers is not in the document]
Comment (maleck13) [reply pkg/broker/deprovision_job.go]: I will follow up with a clear separate issue to allow for that discussion

**Comment by maleck13** [comment]
Will rebase and bring the new Bind and Unbind jobs into line with these changes

File: pkg/broker/deprovision_subscriber.go (hunk 3 above)
Comment (maleck13) [reply pkg/broker/deprovision_subscriber.go]: removed the if entirely as we always want the state to be set

**Comment by maleck13** [comment]
updated with refactored bind and unbind
added new tests for those jobs
changed the agreed on comments

@jmrodri Any further thoughts based on the comments?

I think the only outstanding things are the stutter, which I think could be resolved by removing the JobMsg and just sending through JobState (ie come up with a single type that suits the purposes). Maybe this could be a follow up issue and PR?
The other issues were the for loop ranging over the channel and the log format.

**Comment by rthallisey** [comment]
Looks like we may need to add ```github.com/apex/log``` to glide.  Travis turned up with this error:
```
pkg/broker/binding_job.go:24:2: cannot find package "github.com/apex/log" in any of:
	/home/travis/gopath/src/github.com/openshift/ansible-service-broker/vendor/github.com/apex/log (vendor tree)
	/home/travis/.gimme/versions/go1.8.5.linux.amd64/src/github.com/apex/log (from $GOROOT)
	/home/travis/gopath/src/github.com/apex/log (from $GOPATH)
```

**Comment by maleck13** [comment]
I think this was an error on my part. My editor may have imported it accidentally. I have resolved that issue and rebased on master. Seems a ci job is timing out now

Craig

**Comment by rthallisey** [comment]
Thanks Craig. I just restarted it. We'll see if it happens again.

**Comment by eriknelson** [comment]
@maleck13 Sorry it's taken me a bit to review this. Trying to make my way through a review backlog. I'm guessing this still needs a rebase?

**Comment by maleck13** [comment]
rebased

**Comment by maleck13** [comment]
The CI build is failing, but it is not clear to me how best to find the issue. The log is quite large https://api.travis-ci.org/v3/job/330711368/log.txt

**Comment by rthallisey** [comment]
It's failing on lint. The fix was merged an hour ago: https://github.com/openshift/ansible-service-broker/pull/662
```
=================================
              Lint               
=================================
pkg/apb/types.go:318:2: struct field HttpProxy should be HTTPProxy
pkg/apb/types.go:319:2: struct field HttpsProxy should be HTTPSProxy
Found 2 lint suggestions; failing.
Makefile:27: recipe for target 'lint' failed
make: *** [lint] Error 1
```

**Comment by eriknelson** [comment]
Apologies. I broke the build :)

**Comment by jmrodri** [comment]
I'll take another look at this one now that bind and unbind are in

**Comment by maleck13** [comment]
@rthallisey Thanks for pointer! have rebased again now

**Comment by jmrodri** [comment]
My async bind scripts work fine with this deployed. I like the Binder interface func.
