### PR TITLE
Bug 1535652 - return 200 to bind PUT when a binding already exists

### LINKED ISSUE #649: async bind returns 201 instead of 200
**What happened**:

A PUT request to create a binding should return 200 if the binding already exists, per the OSB API spec. But as seen below, this broker currently returns 201, even though it logs the intent to return 200.
```

[2018-01-17T19:16:43.326Z] [WARNING] - launch_apb_on_bind is enabled, but accepts_incomplete is false, binding may fail
[2018-01-17T19:16:43.341Z] [DEBUG] - Injecting PlanID as parameter: { _apb_plan_id: dev }
[2018-01-17T19:16:43.341Z] [DEBUG] - Injecting ServiceClassID as parameter: { _apb_service_class_id: 1dda1477cace09730bd8ed7a6505607e }
[2018-01-17T19:16:43.341Z] [DEBUG] - Injecting ServiceInstanceID as parameter: { _apb_service_instance_id: 0e124c6d-408e-4b55-8b4a-9c6e6640c444 }
[2018-01-17T19:16:43.342Z] [DEBUG] - already have this binding instance, returning 200
[2018-01-17T19:16:43.342Z] [DEBUG] - bind creds: map[DB_HOST:postgresql DB_NAME:ddcrneradqaeker DB_PASSWORD:qCYtkr2oD1KTZtg5Vig6 DB_PORT:5432 DB_TYPE:postgres DB_USER:ddcrneradqaeker]
172.17.0.7 - - [17/Jan/2018:19:16:43 +0000] "PUT /ansible-service-broker/v2/service_instances/0e124c6d-408e-4b55-8b4a-9c6e6640c444/service_bindings/51b92cd9-3180-480d-af34-16974294c29f HTTP/1.1" 201 216
```

**What you expected to happen**:
return 200

**How to reproduce it**:
1. Configure the broker to run APBs on bind and unbind
2. From the console, initiate a bind
3. Watch the broker log, and after the initial request completes, you will likely see one or more additional PUT requests like the above that show a 201 reponse.

### PR DESCRIPTION
**Pull request by mhrivnak**
fixes #649

### CODE REVIEW

File: pkg/handler/handler.go [hunk 1]
```diff
@@ -565,7 +565,7 @@ func (h handler) bind(w http.ResponseWriter, r *http.Request, params map[string]
 		switch err {
 		case broker.ErrorDuplicate:
 			writeResponse(w, http.StatusConflict, broker.BindResponse{})
-		case broker.ErrorAlreadyProvisioned:
+		case broker.ErrorBindingExists:
```
Comment (jmrodri) [inline pkg/handler/handler.go]: nice catch. this was part of the copy from provision.
